# coding:utf-8
#数据库配置文件
# data for mysql
test01:
    host: localhost
    user: root
    passwd: root
    port: 3306
    db: test01
test02:
    host: localhost
    user: root
    passwd: root
    port: 3306
    db: test01
# data for mangodb
mangodb:
    host: localhost
    port: 27017
    db_name: test
    default_collection: test01